//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.31 at 03:47:14 午後 JST 
//

// modify namespace http://www.openrtp.org/namespaces/rtc -> rtc
@javax.xml.bind.annotation.XmlSchema(namespace = "rtc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openrtp.namespaces.rtc;
