#ifndef INTERFACE1_IDL
#define INTERFACE1_IDL
#include "BasicDataType.idl"

module jp{
    module service{
        /*
        * Interface1_def
        */
        interface Interface1{
            /*
            * op1_def
            */
            void op1();
            /*
            * op2_def
            */
            float op2();
            /*
            * op3_def
            */
            RTC::TimedDouble op3(in RTC::TimedDouble param0, out double param1, inout string param2);
            /*
            * op4_def
            */
            string<10> op4(in string<20> param0);
        };
    };
};

#endif
