#ifndef VALUETYPE_NEST_ASSOSIATION_C1_IDL
#define VALUETYPE_NEST_ASSOSIATION_C1_IDL
#include "ValueType_Nest_Assosiation_C2.idl"

struct ValueType_Nest_Assosiation_C1{
    double attribute18;
    ::ValueType_Nest_Assosiation_C2 ac2;
};

#endif
