#ifndef VALUETYPE_SYSMLNATIVETYPE_IDL
#define VALUETYPE_SYSMLNATIVETYPE_IDL

struct ValueType_SysMLNativeType{
    boolean attribute0;
    double attribute1;
    long attribute2;
    double attribute3;
    double attribute4;
    string attribute5;
};

#endif
