#ifndef VALUETYPE_NEST_IDL
#define VALUETYPE_NEST_IDL
#include "BasicDataType.idl"
#include "ValueType_Nest_C1.idl"
#include "ValueType_Nest_C2.idl"

struct ValueType_Nest{
    ::ValueType_Nest_C1 attribute0;
};

#endif
