#ifndef VALUETYPE_SYSMLNATIVETYPE_MULTIPLICITY_IDL
#define VALUETYPE_SYSMLNATIVETYPE_MULTIPLICITY_IDL

struct ValueType_SysMLNativeType_Multiplicity{
    double attribute7[1];
    double attribute8[1];
    double attribute9[-1];
    double attribute10[-1];
    double attribute11[-1];
    double attribute12[3];
    double attribute13[5];
};

#endif
