#ifndef VALUETYPE_COMMENT_IDL
#define VALUETYPE_COMMENT_IDL
#include "BasicDataType.idl"

/*
* This is comment.<br/>
* これはコメントです
*/
struct ValueType_Comment{
    /*
    * this is attribute comment<br/>
    * これは属性のコメントです
    */
    double attribute20;
};

#endif
