#ifndef USINGIDLTYPE_IDL
#define USINGIDLTYPE_IDL
#include "BasicDataType.idl"

struct UsingIdlType{
    boolean attr1;
    char attr2;
    double attr3;
    float attr4;
    long attr5;
    long double attr6;
    long long attr7;
    octet attr8;
    short attr9;
    string attr10;
    unsigned long attr11;
    unsigned long long attr12;
    unsigned short attr13;
    wchar attr14;
    wstring attr15;
};

#endif
