//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.31 at 03:47:14 午後 JST 
//
@javax.xml.bind.annotation.XmlSchema (
    xmlns = { 
        @javax.xml.bind.annotation.XmlNs(prefix = "rtcExt", 
        namespaceURI="http://www.openrtp.org/namespaces/rtc_ext")
    }
)
package org.openrtp.namespaces.rtc_ext;
